/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.lexer;

import java.io.*;
import java.util.*;
import minipython.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TTab(text, line, pos); }
    Token new1(int line, int pos) { return new TPlus(line, pos); }
    Token new2(int line, int pos) { return new TMinus(line, pos); }
    Token new3(int line, int pos) { return new TMult(line, pos); }
    Token new4(int line, int pos) { return new TDiv(line, pos); }
    Token new5(int line, int pos) { return new TEq(line, pos); }
    Token new6(int line, int pos) { return new TNeq(line, pos); }
    Token new7(int line, int pos) { return new TCeq(line, pos); }
    Token new8(int line, int pos) { return new TExclam(line, pos); }
    Token new9(int line, int pos) { return new TDef(line, pos); }
    Token new10(int line, int pos) { return new TLPar(line, pos); }
    Token new11(int line, int pos) { return new TRPar(line, pos); }
    Token new12(int line, int pos) { return new TLBr(line, pos); }
    Token new13(int line, int pos) { return new TRBr(line, pos); }
    Token new14(int line, int pos) { return new TComma(line, pos); }
    Token new15(int line, int pos) { return new TDot(line, pos); }
    Token new16(int line, int pos) { return new TQmark(line, pos); }
    Token new17(int line, int pos) { return new TSemi(line, pos); }
    Token new18(int line, int pos) { return new TQuote(line, pos); }
    Token new19(int line, int pos) { return new TIf(line, pos); }
    Token new20(int line, int pos) { return new TElif(line, pos); }
    Token new21(int line, int pos) { return new TElse(line, pos); }
    Token new22(int line, int pos) { return new TWhile(line, pos); }
    Token new23(int line, int pos) { return new TFor(line, pos); }
    Token new24(int line, int pos) { return new TIn(line, pos); }
    Token new25(int line, int pos) { return new TPrint(line, pos); }
    Token new26(int line, int pos) { return new TReturn(line, pos); }
    Token new27(int line, int pos) { return new TLess(line, pos); }
    Token new28(int line, int pos) { return new TGreat(line, pos); }
    Token new29(int line, int pos) { return new TTrue(line, pos); }
    Token new30(int line, int pos) { return new TFalse(line, pos); }
    Token new31(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new33(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new34(String text, int line, int pos) { return new TStringLiteral(text, line, pos); }
    Token new35(String text, int line, int pos) { return new TIntegerLiteral(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {63, 63, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {97, 99, 25}, {100, 100, 26}, {101, 101, 27}, {102, 102, 28}, {103, 104, 25}, {105, 105, 29}, {106, 111, 25}, {112, 112, 30}, {113, 113, 25}, {114, 114, 31}, {115, 115, 25}, {116, 116, 32}, {117, 118, 25}, {119, 119, 33}, {120, 122, 25}, },
            {{9, 9, 34}, {10, 32, -2}, {35, 35, 7}, },
            {{9, 9, 35}, {10, 32, -2}, },
            {{9, 9, 35}, {10, 10, 36}, {13, 32, -2}, },
            {{9, 32, -4}, },
            {{61, 61, 37}, },
            {{0, 33, 38}, {34, 34, 39}, {35, 91, 38}, {92, 92, 40}, {93, 127, 38}, },
            {{0, 9, 41}, {10, 10, 42}, {11, 12, 41}, {13, 13, 43}, {14, 127, 41}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 44}, },
            {},
            {{46, 46, 45}, {48, 57, 16}, },
            {},
            {},
            {{61, 61, 46}, },
            {},
            {},
            {{48, 57, 47}, {65, 90, 48}, {97, 122, 49}, },
            {},
            {},
            {{48, 122, -24}, },
            {{48, 90, -24}, {97, 100, 49}, {101, 101, 50}, {102, 122, 49}, },
            {{48, 90, -24}, {97, 107, 49}, {108, 108, 51}, {109, 122, 49}, },
            {{48, 90, -24}, {97, 97, 52}, {98, 110, 49}, {111, 111, 53}, {112, 122, 49}, },
            {{48, 90, -24}, {97, 101, 49}, {102, 102, 54}, {103, 109, 49}, {110, 110, 55}, {111, 122, 49}, },
            {{48, 90, -24}, {97, 113, 49}, {114, 114, 56}, {115, 122, 49}, },
            {{48, 100, -28}, {101, 101, 57}, {102, 122, 49}, },
            {{48, 113, -32}, {114, 114, 58}, {115, 122, 49}, },
            {{48, 90, -24}, {97, 103, 49}, {104, 104, 59}, {105, 122, 49}, },
            {{9, 35, -3}, },
            {{9, 32, -4}, },
            {{9, 32, -4}, },
            {},
            {{0, 127, -8}, },
            {},
            {{34, 34, 60}, {92, 92, 61}, {110, 110, 62}, {114, 114, 63}, {116, 116, 64}, },
            {{0, 127, -9}, },
            {},
            {{10, 10, 65}, },
            {{48, 57, 44}, },
            {{48, 57, 66}, },
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 101, -31}, {102, 102, 67}, {103, 122, 49}, },
            {{48, 90, -24}, {97, 104, 49}, {105, 105, 68}, {106, 114, 49}, {115, 115, 69}, {116, 122, 49}, },
            {{48, 107, -29}, {108, 108, 70}, {109, 122, 49}, },
            {{48, 113, -32}, {114, 114, 71}, {115, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 104, -53}, {105, 105, 72}, {106, 122, 49}, },
            {{48, 90, -24}, {97, 115, 49}, {116, 116, 73}, {117, 122, 49}, },
            {{48, 90, -24}, {97, 116, 49}, {117, 117, 74}, {118, 122, 49}, },
            {{48, 104, -53}, {105, 105, 75}, {106, 122, 49}, },
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {},
            {{48, 57, 66}, },
            {{48, 122, -24}, },
            {{48, 101, -31}, {102, 102, 76}, {103, 122, 49}, },
            {{48, 100, -28}, {101, 101, 77}, {102, 122, 49}, },
            {{48, 90, -24}, {97, 114, 49}, {115, 115, 78}, {116, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 90, -24}, {97, 109, 49}, {110, 110, 79}, {111, 122, 49}, },
            {{48, 116, -60}, {117, 117, 80}, {118, 122, 49}, },
            {{48, 100, -28}, {101, 101, 81}, {102, 122, 49}, },
            {{48, 107, -29}, {108, 108, 82}, {109, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -28}, {101, 101, 83}, {102, 122, 49}, },
            {{48, 115, -59}, {116, 116, 84}, {117, 122, 49}, },
            {{48, 113, -32}, {114, 114, 85}, {115, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 100, -28}, {101, 101, 86}, {102, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 109, -74}, {110, 110, 87}, {111, 122, 49}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 0, 31, 31, 31, 8, 18, -1, 10, 11, 3, 1, 14, 2, 15, 4, 35, 17, 27, 5, 28, 16, 33, 12, 13, 33, 33, 33, 33, 33, 33, 33, 33, 33, 31, 31, 31, 6, -1, 34, -1, -1, 32, 32, 35, 35, 7, 33, 33, 33, 33, 33, 33, 33, 19, 24, 33, 33, 33, 33, -1, -1, -1, -1, -1, 32, 35, 9, 33, 33, 33, 23, 33, 33, 33, 33, 20, 21, 33, 33, 33, 29, 33, 30, 25, 33, 22, 26, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
