/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.analysis;

import minipython.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAGoal(AGoal node);
    void caseAStatementCommands(AStatementCommands node);
    void caseAFunctionCommands(AFunctionCommands node);
    void caseAFunctiondeclarationFunction(AFunctiondeclarationFunction node);
    void caseAArg1(AArg1 node);
    void caseAArg2(AArg2 node);
    void caseAArgumentArgument(AArgumentArgument node);
    void caseACexp(ACexp node);
    void caseAIfStatement(AIfStatement node);
    void caseAWhileStatement(AWhileStatement node);
    void caseAForStatement(AForStatement node);
    void caseAReturnStatement(AReturnStatement node);
    void caseAPrintStatement(APrintStatement node);
    void caseAAllocation1Statement(AAllocation1Statement node);
    void caseAAllocation2Statement(AAllocation2Statement node);
    void caseAFunctioncallStatement(AFunctioncallStatement node);
    void caseASomethingMultiplication(ASomethingMultiplication node);
    void caseAMultiplicationMultiplication(AMultiplicationMultiplication node);
    void caseADivisionMultiplication(ADivisionMultiplication node);
    void caseAIdentifierSomething(AIdentifierSomething node);
    void caseANumberSomething(ANumberSomething node);
    void caseAParSomething(AParSomething node);
    void caseACval(ACval node);
    void caseAMultiplicationExpression(AMultiplicationExpression node);
    void caseAAdditionExpression(AAdditionExpression node);
    void caseASubtractionExpression(ASubtractionExpression node);
    void caseAExp2Expression(AExp2Expression node);
    void caseAFunctioncallExpression(AFunctioncallExpression node);
    void caseAExp3Expression(AExp3Expression node);
    void caseAGreatSymb(AGreatSymb node);
    void caseALessSymb(ALessSymb node);
    void caseANeqSymb(ANeqSymb node);
    void caseACeqSymb(ACeqSymb node);
    void caseACompComparison(ACompComparison node);
    void caseATrueComparison(ATrueComparison node);
    void caseAFalseComparison(AFalseComparison node);
    void caseAFunctioncallFunctionCall(AFunctioncallFunctionCall node);
    void caseAArgsArglist(AArgsArglist node);
    void caseANumberValue(ANumberValue node);
    void caseAStringValue(AStringValue node);
    void caseAIntegerNumber(AIntegerNumber node);
    void caseAIdIdentifier(AIdIdentifier node);

    void caseTTab(TTab node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTEq(TEq node);
    void caseTNeq(TNeq node);
    void caseTCeq(TCeq node);
    void caseTExclam(TExclam node);
    void caseTDef(TDef node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBr(TLBr node);
    void caseTRBr(TRBr node);
    void caseTComma(TComma node);
    void caseTDot(TDot node);
    void caseTQmark(TQmark node);
    void caseTSemi(TSemi node);
    void caseTQuote(TQuote node);
    void caseTIf(TIf node);
    void caseTElif(TElif node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTFor(TFor node);
    void caseTIn(TIn node);
    void caseTPrint(TPrint node);
    void caseTReturn(TReturn node);
    void caseTLess(TLess node);
    void caseTGreat(TGreat node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTBlank(TBlank node);
    void caseTLineComment(TLineComment node);
    void caseTId(TId node);
    void caseTStringLiteral(TStringLiteral node);
    void caseTIntegerLiteral(TIntegerLiteral node);
    void caseTClass(TClass node);
    void caseEOF(EOF node);
}
