/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(5), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(7), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(8), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(8), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(8), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(9), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(9), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(9), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(10), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(10), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(10), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(10), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(10), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(10), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(10), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(10), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(11), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(12), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(12), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(12), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(12), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(13), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(13), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(14), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(14), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(15), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(15), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(16), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(16), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(17), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(17), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(18), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(18), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(19), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(19), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgramme node1 = (PProgramme) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pprogrammeNode1 = new AProgramme(listNode2);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogrammeNode1 = new AProgramme(listNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatementCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFunctionCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFunctionDeclarationFunction(tidNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        PArgument pargumentNode3;
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
	if(pargumentNode3 != null)
	{
	  listNode4.add(pargumentNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunctionDeclarationFunction(tidNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }
        {
        }

        pargumentNode1 = new AArgument(tidNode2, listNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PArgumentAllocation pargumentallocationNode3;
        pargumentallocationNode3 = (PArgumentAllocation)nodeArrayList2.get(0);
	if(pargumentallocationNode3 != null)
	{
	  listNode4.add(pargumentallocationNode3);
	}
        }
        {
        }

        pargumentNode1 = new AArgument(tidNode2, listNode4, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, listNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode6 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PArgumentAllocation pargumentallocationNode3;
        pargumentallocationNode3 = (PArgumentAllocation)nodeArrayList2.get(0);
	if(pargumentallocationNode3 != null)
	{
	  listNode4.add(pargumentallocationNode3);
	}
        }
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, listNode4, listNode6);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgumentAllocation pargumentallocationNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pargumentallocationNode1 = new AArgumentAllocation(pvalueNode2);
        }
	nodeList.add(pargumentallocationNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAnotherArgument panotherargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        }

        panotherargumentNode1 = new AAnotherArgument(tidNode2, listNode3);
        }
	nodeList.add(panotherargumentNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAnotherArgument panotherargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        PArgumentAllocation pargumentallocationNode3;
        pargumentallocationNode3 = (PArgumentAllocation)nodeArrayList3.get(0);
	if(pargumentallocationNode3 != null)
	{
	  listNode4.add(pargumentallocationNode3);
	}
        }

        panotherargumentNode1 = new AAnotherArgument(tidNode2, listNode4);
        }
	nodeList.add(panotherargumentNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList3.get(0);
        tidNode3 = (TId)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAllocation1Statement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAllocation1Statement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AAllocation2Statement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AAllocation2Statement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pstatementNode1 = new AFunctionCallStatement(tidNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new AFunctionCallStatement(tidNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PArgumentsList pargumentslistNode3;
        pargumentslistNode3 = (PArgumentsList)nodeArrayList3.get(0);
	if(pargumentslistNode3 != null)
	{
	  listNode4.add(pargumentslistNode3);
	}
        }

        pstatementNode1 = new AFunctionCallStatement(tidNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        PArgumentsList pargumentslistNode3;
        pargumentslistNode3 = (PArgumentsList)nodeArrayList4.get(0);
	if(pargumentslistNode3 != null)
	{
	  listNode4.add(pargumentslistNode3);
	}
        }

        pstatementNode1 = new AFunctionCallStatement(tidNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAnotherExpression panotherexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        panotherexpressionNode1 = new AAnotherExpression(pexpressionNode2);
        }
	nodeList.add(panotherexpressionNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAdditionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubtractionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultiplicationExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivisionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentifierExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pexpressionNode1 = new AFunctionCallExpression(tidNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PArgumentsList pargumentslistNode3;
        pargumentslistNode3 = (PArgumentsList)nodeArrayList3.get(0);
	if(pargumentslistNode3 != null)
	{
	  listNode4.add(pargumentslistNode3);
	}
        }

        pexpressionNode1 = new AFunctionCallExpression(tidNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AIdParExpression(tidNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AParValuesExpression(pvalueNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AParValuesExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AParExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAnotherValue panothervalueNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        panothervalueNode1 = new AAnotherValue(pvalueNode2);
        }
	nodeList.add(panothervalueNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALessComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ACeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgumentsList pargumentslistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        pargumentslistNode1 = new AArgumentsList(pexpressionNode2, listNode3);
        }
	nodeList.add(pargumentslistNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgumentsList pargumentslistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pargumentslistNode1 = new AArgumentsList(pexpressionNode2, listNode4);
        }
	nodeList.add(pargumentslistNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TIntegerLiteral tintegerliteralNode2;
        tintegerliteralNode2 = (TIntegerLiteral)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(tintegerliteralNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringliteralNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PAnotherArgument panotherargumentNode1;
        panotherargumentNode1 = (PAnotherArgument)nodeArrayList1.get(0);
	if(panotherargumentNode1 != null)
	{
	  listNode2.add(panotherargumentNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PAnotherArgument panotherargumentNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        panotherargumentNode2 = (PAnotherArgument)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(panotherargumentNode2 != null)
	{
	  listNode3.add(panotherargumentNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PAnotherExpression panotherexpressionNode1;
        panotherexpressionNode1 = (PAnotherExpression)nodeArrayList1.get(0);
	if(panotherexpressionNode1 != null)
	{
	  listNode2.add(panotherexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PAnotherExpression panotherexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        panotherexpressionNode2 = (PAnotherExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(panotherexpressionNode2 != null)
	{
	  listNode3.add(panotherexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PAnotherValue panothervalueNode1;
        panothervalueNode1 = (PAnotherValue)nodeArrayList1.get(0);
	if(panothervalueNode1 != null)
	{
	  listNode2.add(panothervalueNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PAnotherValue panothervalueNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        panothervalueNode2 = (PAnotherValue)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(panothervalueNode2 != null)
	{
	  listNode3.add(panothervalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {9, SHIFT, 2}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, REDUCE, 61}, },
			{{-1, ERROR, 2}, {30, SHIFT, 15}, },
			{{-1, ERROR, 3}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 4}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 5}, {30, SHIFT, 27}, },
			{{-1, ERROR, 6}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 7}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 8}, {5, SHIFT, 30}, {10, SHIFT, 31}, {12, SHIFT, 32}, },
			{{-1, ERROR, 9}, {34, ACCEPT, -1}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {9, SHIFT, 2}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 14}, {0, SHIFT, 34}, {18, SHIFT, 35}, {21, SHIFT, 36}, {22, SHIFT, 37}, {24, SHIFT, 38}, {25, SHIFT, 39}, {30, SHIFT, 40}, },
			{{-1, ERROR, 15}, {10, SHIFT, 41}, },
			{{-1, ERROR, 16}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 17}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 40}, {10, SHIFT, 44}, {12, SHIFT, 45}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 21}, {1, SHIFT, 46}, {2, SHIFT, 47}, {6, SHIFT, 48}, {7, SHIFT, 49}, {26, SHIFT, 50}, {27, SHIFT, 51}, },
			{{-1, REDUCE, 34}, {3, SHIFT, 52}, {4, SHIFT, 53}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 24}, {17, SHIFT, 54}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 26}, {17, SHIFT, 55}, },
			{{-1, ERROR, 27}, {23, SHIFT, 56}, },
			{{-1, REDUCE, 21}, {1, SHIFT, 46}, {2, SHIFT, 47}, {14, SHIFT, 57}, },
			{{-1, REDUCE, 19}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, ERROR, 30}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 31}, {10, SHIFT, 16}, {11, SHIFT, 61}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 32}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 62}, },
			{{-1, ERROR, 35}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 36}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 37}, {30, SHIFT, 67}, },
			{{-1, ERROR, 38}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 39}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 40}, {5, SHIFT, 70}, {10, SHIFT, 71}, {12, SHIFT, 72}, },
			{{-1, ERROR, 41}, {11, SHIFT, 73}, {30, SHIFT, 74}, },
			{{-1, ERROR, 42}, {1, SHIFT, 46}, {2, SHIFT, 47}, {11, SHIFT, 76}, },
			{{-1, ERROR, 43}, {13, SHIFT, 77}, {14, SHIFT, 78}, },
			{{-1, ERROR, 44}, {10, SHIFT, 16}, {11, SHIFT, 81}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 45}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 46}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 47}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 48}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 49}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 50}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 51}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 52}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 53}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 54}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 55}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 56}, {30, SHIFT, 94}, },
			{{-1, ERROR, 57}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 23}, {14, SHIFT, 57}, },
			{{-1, REDUCE, 25}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 53}, {1, SHIFT, 46}, {2, SHIFT, 47}, {14, SHIFT, 57}, },
			{{-1, ERROR, 63}, {11, SHIFT, 98}, },
			{{-1, ERROR, 64}, {1, SHIFT, 46}, {2, SHIFT, 47}, {13, SHIFT, 99}, },
			{{-1, ERROR, 65}, {17, SHIFT, 100}, },
			{{-1, ERROR, 66}, {17, SHIFT, 101}, },
			{{-1, ERROR, 67}, {23, SHIFT, 102}, },
			{{-1, REDUCE, 22}, {1, SHIFT, 46}, {2, SHIFT, 47}, {14, SHIFT, 57}, },
			{{-1, REDUCE, 20}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, ERROR, 70}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 71}, {10, SHIFT, 16}, {11, SHIFT, 105}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 72}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 73}, {17, SHIFT, 108}, },
			{{-1, REDUCE, 6}, {5, SHIFT, 109}, {14, SHIFT, 110}, },
			{{-1, ERROR, 75}, {11, SHIFT, 114}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 78}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 65}, },
			{{-1, ERROR, 80}, {13, SHIFT, 116}, {14, SHIFT, 78}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 82}, {11, SHIFT, 118}, },
			{{-1, ERROR, 83}, {1, SHIFT, 46}, {2, SHIFT, 47}, {13, SHIFT, 119}, },
			{{-1, REDUCE, 35}, {3, SHIFT, 52}, {4, SHIFT, 53}, },
			{{-1, REDUCE, 36}, {3, SHIFT, 52}, {4, SHIFT, 53}, },
			{{-1, REDUCE, 51}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 52}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 50}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 49}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 94}, {17, SHIFT, 120}, },
			{{-1, REDUCE, 33}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 54}, {14, SHIFT, 57}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 99}, {5, SHIFT, 121}, },
			{{-1, ERROR, 100}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 101}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 102}, {30, SHIFT, 124}, },
			{{-1, REDUCE, 24}, {14, SHIFT, 57}, },
			{{-1, REDUCE, 26}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 106}, {11, SHIFT, 125}, },
			{{-1, ERROR, 107}, {1, SHIFT, 46}, {2, SHIFT, 47}, {13, SHIFT, 126}, },
			{{-1, ERROR, 108}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 109}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, ERROR, 110}, {30, SHIFT, 129}, },
			{{-1, REDUCE, 7}, {14, SHIFT, 110}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 8}, {14, SHIFT, 110}, },
			{{-1, ERROR, 114}, {17, SHIFT, 132}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 66}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 120}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 121}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 124}, {17, SHIFT, 135}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 126}, {5, SHIFT, 136}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, {5, SHIFT, 109}, },
			{{-1, REDUCE, 9}, {14, SHIFT, 110}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 132}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 27}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
			{{-1, ERROR, 135}, {0, SHIFT, 1}, {18, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {24, SHIFT, 6}, {25, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 136}, {10, SHIFT, 16}, {12, SHIFT, 17}, {30, SHIFT, 18}, {31, SHIFT, 19}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 28}, {1, SHIFT, 46}, {2, SHIFT, 47}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 9}, },
			{{-1, 10}, {13, 33}, },
			{{-1, 11}, },
			{{-1, 75}, },
			{{-1, 111}, {129, 137}, },
			{{-1, 112}, {113, 131}, {130, 131}, },
			{{-1, 12}, {54, 92}, {55, 93}, {100, 122}, {101, 123}, {108, 127}, {120, 133}, {132, 138}, {135, 139}, },
			{{-1, 58}, {59, 96}, {97, 96}, {103, 96}, },
			{{-1, 21}, {6, 28}, {7, 29}, {16, 42}, {30, 60}, {31, 62}, {32, 64}, {38, 68}, {39, 69}, {44, 62}, {45, 83}, {48, 86}, {49, 87}, {50, 88}, {51, 89}, {57, 95}, {70, 104}, {71, 62}, {72, 107}, {121, 134}, {136, 140}, },
			{{-1, 22}, {46, 84}, {47, 85}, },
			{{-1, 23}, {52, 90}, {53, 91}, },
			{{-1, 79}, {80, 117}, },
			{{-1, 24}, {4, 26}, {35, 65}, {36, 66}, },
			{{-1, 63}, {44, 82}, {71, 106}, },
			{{-1, 25}, {17, 43}, {78, 115}, {109, 128}, },
			{{-1, 13}, },
			{{-1, 113}, {111, 130}, },
			{{-1, 14}, },
			{{-1, 59}, {62, 97}, {68, 103}, },
			{{-1, 80}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, 'if', 'while', 'for', 'print', 'return', id",
			"expecting: id",
			"expecting: '(', '[', id, string literal, integer literal",
			"expecting: '=', '(', '['",
			"expecting: EOF",
			"expecting: '('",
			"expecting: string literal, integer literal",
			"expecting: tab, '+', '-', '*', '/', '!=', '==', 'def', '(', ')', '[', ']', ',', ':', 'if', 'while', 'for', 'print', 'return', '<', '>', id, EOF",
			"expecting: tab, '+', '-', '*', '/', '!=', '==', 'def', ')', ']', ',', ':', 'if', 'while', 'for', 'print', 'return', '<', '>', id, EOF",
			"expecting: '+', '-', '!=', '==', '<', '>'",
			"expecting: ':'",
			"expecting: 'in'",
			"expecting: tab, '+', '-', 'def', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, '+', '-', 'def', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '(', ')', '[', id, string literal, integer literal",
			"expecting: ')', id",
			"expecting: '+', '-', ')'",
			"expecting: ']', ','",
			"expecting: tab, 'def', ')', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, 'def', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '+', '-', ')', ','",
			"expecting: ')'",
			"expecting: '+', '-', ']'",
			"expecting: '=', ')', ','",
			"expecting: '+', '-', ':'",
			"expecting: tab, '+', '-', 'def', ')', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: ')', ','",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 2, 3, 3, 4, 5, 0, 0, 0, 0, 1, 6, 3, 7, 8, 9, 9, 10, 9, 9, 11, 9, 11, 12, 13, 14, 3, 15, 3, 0, 1, 3, 3, 2, 3, 3, 4, 16, 17, 18, 15, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 2, 3, 19, 20, 14, 0, 21, 22, 23, 11, 11, 12, 13, 14, 3, 15, 3, 11, 24, 22, 9, 9, 7, 18, 18, 9, 22, 23, 9, 9, 25, 25, 25, 25, 9, 9, 0, 0, 11, 26, 19, 27, 0, 28, 1, 1, 2, 20, 14, 0, 22, 23, 1, 7, 2, 27, 27, 27, 11, 18, 9, 18, 9, 9, 1, 3, 0, 0, 11, 0, 28, 0, 27, 24, 27, 27, 1, 0, 14, 1, 3, 27, 0, 0, 14, 
        };*/
}
